MTDSA:26823
hmrc/individuals-capital-gains-income-api pull request #37
Opened 2024-12-12 16:38 UTC by DavouJ

2024-12-12 16:41 UTC, MarkAKelly reviewed
Would you mind adding a description of the change in the title please @DavouJ

2024-12-13 13:23 UTC, AhmadZNaeem commented on resources/public/api/conf/common/errors.md
> +Read the [reference guide](https://developer.service.hmrc.gov.uk/api-documentation/docs/reference-guide#errors) for more information about errors.
Environment specific url can be used: `[reference guide](/api-documentation/docs/reference-guide#errors)`

2024-12-13 13:26 UTC, AhmadZNaeem commented on resources/public/api/conf/common/testing.md
> +You can use the Sandbox environment to [test this API](https://developer.service.hmrc.gov.uk/api-documentation/docs/testing). You can test different scenarios in the Sandbox by passing the
Environment specific url can be used `[test this API](/api-documentation/docs/testing)`

2024-12-13 13:26 UTC, AhmadZNaeem commented on resources/public/api/conf/common/testing.md
> +If you have a specific testing need that is not supported in the Sandbox, [contact our Software Developers Support Team](https://developer.service.hmrc.gov.uk/developer/support).
Environment specific url can be used `[contact our Software Developers Support Team](/developer/support)`

2024-12-13 13:28 UTC, AhmadZNaeem commented on resources/public/api/conf/common/versioning.md
> +Read the [reference guide](https://developer.service.hmrc.gov.uk/api-documentation/docs/reference-guide#versioning) for more information about API versioning.
Environment specific url can be used: `[reference guide](/api-documentation/docs/reference-guide#versioning)`

2024-12-13 16:41 UTC, AhmadZNaeem commented
I'm away on leave so can someone else approve this ticket once comments have been addressed. Thank you

2024-12-17 11:43 UTC, benryan1790 requested changes

2024-12-17 11:43 UTC, benryan1790 commented on resources/public/api/conf/common/testing.md
> +If you have a specific testing need that is not supported in the Sandbox, [contact our Software Developers Support Team](]/developer/support).
errant closing square bracket in the link

2024-12-17 15:32 UTC, benryan1790 approved these changes

2024-12-17 15:33 UTC, merged